### ISSUE TITLE
Default brightness/saturation comments

### ISSUE THREAD

**Issue by techmindorg** [simoninns/ld-colourfilter#2]
In lines 61, 62, you've inherited my comments, which date from much older versions of the code
    setSaturation(100);         // colour saturation control: 0-100, 64typ.
    setBrightness(100);         // 70ish for a perfect-level capture

The comments should be updated to both say "nominally 100 for a perfect level capture (blanking at 64dec, peak white at 211dec)".
Adjustments away from 100 should only be needed to compensate for signals sampled at the wrong "gain" and maybe to compensate for HF roll-off or MTF fixups - or for aesthetic reasons.

**Comment by simoninns** [comment]
Fixed in commit c141315
